database:
    hostname: localhost
    username: postgres
    password: dygim00n
    database: all4m

debug: true


monolog:
    name: 'test'
    handlers:
        main:
            type: 'stream'
            path: '/tmp/log'
            level: 'notice'

