home:
    method: get
    pattern: /
    action: All4m\Home::index

play:
    method: get
    pattern: /play/{id}
    action: All4m\Home::play

video_next:
    method: get
    pattern: /video/next
    action: All4m\Video::next

video_flag:
    method: get
    pattern: /video/flag/{id}
    action: All4m\Video::flag

video_get:
    method: get
    pattern: /video/get/{id}
    action: All4m\Video::getTrack

video_search:
    method: get
    pattern: /search/{query}
    action: All4m\Video::search
